passdb {
  driver = passwd-file
  args = scheme=PLAIN username_format=%u /etc/dovecot/users
}
userdb {
  driver = passwd-file
  args = username_format=%u /etc/dovecot/users
  default_fields = uid=dovecot gid=dovecot home=/srv/mail/%n
}
mail_location = maildir:/srv/mail/%n
ssl = no
disable_plaintext_auth = no
auth_mechanisms = plain login
